home/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index, name='index'),

]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as OrderViews
from user import views as UserViews
urlpatterns = [
    path('product/', include('product.urls')),
    path('', include('home.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('login/', UserViews.login, name='login'),
    path('sign_up/', UserViews.sign_up, name='login'),
    path('logout/', UserViews.logout, name='login'),

    path('shopcart/', OrderViews.shopcart, name='shopcart'),

    path('home/', include('home.urls')),
    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('contact/',views.contactus, name='contactus'),
    path('about/', views.aboutus, name='aboutus'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),

]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
from django.forms import ModelForm, TextInput, Textarea


class Setting(models.Model):
    STATUS = (
        ('True', 'Mavjud'),
        ('False', 'Mavjud emas'),
    )
    title = models.CharField(max_length=222)
    keywords = models.CharField(max_length=222)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=222)
    address = models.CharField(max_length=222, blank=True)
    phone = models.CharField(max_length=222, blank=True)
    fax = models.CharField(max_length=222, blank=True)
    email = models.CharField(max_length=222, blank=True)
    smtserver = models.CharField(max_length=222, blank=True)
    smtemail = models.CharField(max_length=222, blank=True)
    smtpassword = models.CharField(max_length=222, blank=True)
    smtport = models.CharField(max_length=222, blank=True)
    icon = models.ImageField(upload_to='images/', blank=True)
    facebook = models.CharField(max_length=222, blank=True)
    instagram = models.CharField(max_length=222, blank=True)
    twitter = models.CharField(max_length=222, blank=True)
    youtube = models.CharField(max_length=222, blank=True)
    telegram = models.CharField(max_length=222, blank=True)
    aboutus = RichTextUploadingField()
    contact = RichTextUploadingField()
    references = RichTextUploadingField()
    status = models.CharField(max_length=155, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ContactMessage(models.Model):
    STATUS = (
        ('New', 'Yangi'),
        ('Read', 'Read'),
        ('Closed', 'Yopilgan'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.TextField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=50)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name','email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder':  'Name'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your message', 'rows': '5'}),
        }

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

from django.utils.safestring import mark_safe

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=255)
    city = models.CharField(blank=True, max_length=50)
    country = models.CharField(blank=True, max_length=50)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username
    def user_name(self):
        return self.user.first_name + '' + self.user.last_name + '[' + self.user.username + ']'

    def image_tag(self):
        return mark_safe('<img src="{}" height="50">'.format(self.image.url))

    image_tag.short_description = 'Image'

home/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)
    catid = forms.IntegerField()

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, FileInput,Select
from user.models import UserProfile

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=255, label='Username')
    email = forms.CharField(max_length=255, label='Email')
    first_name = forms.CharField(max_length=255, label='Firstname')
    last_name = forms.CharField(max_length=255, label='Lastname')
    class Meta:
        model=User
        fields = ('username', 'email', 'first_name', 'last_name')

class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {
            'username': TextInput(attrs={'class': 'input', 'placeholder': 'Username'}),
            'email': EmailInput(attrs={'class': 'input', 'placeholder': 'Email'}),
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'Firstname'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'Lastname'}),
        }
        CITY = [
            ('Tashkent' 'Tashkent'),
            ('Fargana' 'Fargana'),
            ('Namangan' 'Namangan'),
            ('Los Andijon' 'Los Andijon'),
            ('Surxandaryo' 'Surxandaryo'),
            ('Qashqadaryo' 'Qashqadaryo'),
            ('Navoi' 'Navoi'),
            ('Sirdaryo' 'Sirdaryo'),
            ('Jizzax' 'Jizzax'),
            ('Bukhara' 'Bukhara'),
            ('Xorazim' 'Xorazim'),
            ('Samarqand' 'Samarqand'),
            ('Qoraqolpogiston' 'Qoraqolpogiston'),

        ]
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'Phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'Address'}),
            'city': Select(attrs={'class': 'input', 'placeholder': 'City'}),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'Country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'Image'}),
        }

home/views.py
import json

from django.contrib import messages
from django.http import HttpResponseRedirect, request
from django.shortcuts import render, HttpResponse

from product.models import Category, Product, Images, Comment
from .forms import SearchForm
from .models import Setting, ContactForm, ContactMessage


# Create your views here.
def index(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    products_slider = Product.objects.all().order_by('id')[:8]
    products_latest = Product.objects.all().order_by('-id')[:8]
    products_picked = Product.objects.all().order_by('?')[:8]
    page = "home"
    context ={'setting': setting,
              'page': page,
              'category':category,
              'products_slider':products_slider,
              'products_latest': products_latest,
              'products_picked':products_picked,
              }
    return render(request, 'index.html', context)


def contactus(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactMessage()
            data.name = form.cleaned_data['name']
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, 'Sizning xabaringiz qabul qilindi!Rahmat')
            return HttpResponseRedirect('/contact')
    setting = Setting.objects.get(pk=1)
    form = ContactForm
    context = {'setting': setting, 'form': form, }
    return render(request, 'contact.html', context)


def aboutus(request):
    setting = Setting.objects.get(pk=1)
    context = {'setting':setting,}
    return render(request, 'about.html', context)


def category_products(request, id, slug):
    category = Category.objects.all()
    #catdata = Category.objects.get(pk=1)
    products = Product.objects.filter(category_id=id)
    context = {
        'category': category,
        #'catdata': catdata,
        'products': products,
    }
    return render(request, 'category_products.html', context)

def search(request):
    if request.method=='POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            catid = form.cleaned_data['catid']
            if catid == 0:
                products = Product.objects.filter(title__icontains=query)
            else:
                products = Product.objects.filter(title__icontains=query, category_id=catid)

            category = Category.objects.all()
            context = {
                'products': products,
                'query': query,
                'category': category,
            }
            return render(request, 'search.html', context)
    return HttpResponseRedirect('/')


def search_auto(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        products = Product.objects.filter(title__icontains=q)
        results = []
        for rs in products:
            products_json = {}
            products_json = rs.title
            results.append(products_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


def product_detail(request, id, slug):
    category = Category.objects.all()
    product = Product.objects.get(pk=id)
    images = Images.objects.filter(product_id=id)
    comments = Comment.objects.filter(product_id=id, status='True')
    context = {
        'category': category,
        'product': product,
        'images': images,
        'comments': comments,
    }
    return render(request, 'product_detail.html', context)

home/templates/about.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %}About Us -{{ setting.title }} {% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}

{% block body %}
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">About Us</li>
            </ul>
        </div>
    </div>

    <div class="section">
        <div class="container">
            <div class="row">
                {{ setting.aboutus|safe }}
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %} {% include 'footer.html' %}{% endblock %}

home/templates/category_products.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %}{{ category.title }}Products {% endblock %}
{% block keywords %}{{ category.keywords }}{% endblock %}
{% block description %}{{ category.description }}{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}

{% block body %}
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">{{ category.title }} Products</li>
            </ul>
        </div>
    </div>

    <div class="section">
        <div class="container">
            <div class="row">
               {% for rs in products %}
                    <tr>
                        <td class="thumb"><a href="/product/{{ rs.id }}/{{ rs.slug }}">
                            <img src="{{ rs.image.url }}" style="height: 100px" alt=""></a></td>
                        <td class="details">
                            <a href="/product/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a>
                        </td>
                        <td class="price text-center"><strong>{{ rs.price }} so'm</strong></td>
                        <td class="qty text-center"><input class="input" type="number" value="1"></td>
                        <td class="text-right"><a href="/order/addtoshopcart/{{ rs.id }}" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i>Add to shopcart</a></td>
                    </tr>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %} {% include 'footer.html' %}{% endblock %}

home/templates/contact.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %}Contact Us - {{ setting.title }}{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}

{% block body %}
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Contact Us</li>
            </ul>
        </div>
    </div>

    <div class="section">
         <div class="container">
             <div class="row">
                 <div class="col-md-4">
                     <form id="contact-form" class="clearfix" method="post">

                         <div class="billing-details">
                             {% csrf_token %}
                             <div class="section-title">
                                 <h3 class="title">Contact Form</h3>
                             {% if messages %}
                                 {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                        {{ message }}
                                    </div>
                                 {% endfor %}
                             {% endif %}
                             </div>
                             {{ form.as_table }}
                             <input type="submit" value="SEND FORM">
                         </div>
                     </form>
                 </div>
                 <div class="col-md-8">
                     <div class="contact">
                         <div class="section-title">
                             <h3>Contact Information</h3>
                         </div>
                         <div class="text">
                             {{ setting.contact|safe }}
                         </div>

                     </div>
                 </div>

             </div>
         </div>
    </div>
{% endblock %}
{% block footer %} {% include 'footer.html' %}{% endblock %}

home/templates/content.html
{% load static %}


	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">Oxirgi Qo'shilgan Maxsulotlar</h2>
					</div>
				</div>
				<!-- section title -->
                {% for rs in products_latest %}
				<!-- Product Single -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="product product-single">
						<div class="product-thumb">
							<a href="/product/{{ rs.id }}/{{ rs.slug }}" class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</a>
							<img src="{{ rs.image.url }}" style="height: 200px" alt="">
						</div>
						<div class="product-body">
							<h3 class="product-price">{{rs.price}}so'm</h3>
							<div class="product-rating">
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star-o empty"></i>
							</div>
							<h2 class="product-name"><a href="#">{{ rs.title }}</a></h2>
							<div class="product-btns">
								<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
								<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
								<a href="/order/addtoshopcart/{{ rs.id }}" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
							</div>
						</div>
					</div>
				</div>
				<!-- /Product Single -->
                {% endfor %}

			<!-- row -->
			<div class="row">
				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">Siz Uchun Tafsiya Qilamiz</h2>
					</div>
				</div>
				<!-- section title -->
                {% for rs in products_picked %}
				<!-- Product Single -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="product product-single">
						<div class="product-thumb">
							<a href="/product/{{ rs.id }}/{{ rs.slug }}" class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</a>
							<img src="{{ rs.image.url }}" alt="" style="height: 200px">
						</div>
						<div class="product-body">
							<h3 class="product-price">{{rs.price}}so'm</h3>
							<div class="product-rating">
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star-o empty"></i>
							</div>
							<h2 class="product-name"><a href="#">{{ rs.title }}</a></h2>
							<div class="product-btns">
								<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
								<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
								<a href="/order/addtoshopcart/{{ rs.id }}" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
							</div>
						</div>
					</div>
				</div>
				<!-- /Product Single -->
                {% endfor %}


		<!-- /container -->

	<!-- /section -->

                </div>
            </div>
        </div>
    </div>

home/templates/footer.html
{% load static %}
	<!-- FOOTER -->
	<footer id="footer" class="section section-grey">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<!-- footer logo -->
						<div class="footer-logo">
							<a class="logo" href="#">
		            <img src="./img/logo.png" alt="">
		          </a>
						</div>
						<!-- /footer logo -->

						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>

						<!-- footer social -->
						<ul class="footer-social">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
						</ul>
						<!-- /footer social -->
					</div>
				</div>
				<!-- /footer widget -->

				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">My Account</h3>
						<ul class="list-links">
							<li><a href="#">My Account</a></li>
							<li><a href="#">My Wishlist</a></li>
							<li><a href="#">Compare</a></li>
							<li><a href="#">Checkout</a></li>
							<li><a href="#">Login</a></li>
						</ul>
					</div>
				</div>
				<!-- /footer widget -->

				<div class="clearfix visible-sm visible-xs"></div>

				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">Customer Service</h3>
						<ul class="list-links">
							<li><a href="#">About Us</a></li>
							<li><a href="#">Shiping & Return</a></li>
							<li><a href="#">Shiping Guide</a></li>
							<li><a href="#">FAQ</a></li>
						</ul>
					</div>
				</div>
				<!-- /footer widget -->

				<!-- footer subscribe -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">Stay Connected</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
						<form>
							<div class="form-group">
								<input class="input" placeholder="Enter Email Address">
							</div>
							<button class="primary-btn">Join Newslatter</button>
						</form>
					</div>
				</div>
				<!-- /footer subscribe -->
			</div>
			<!-- /row -->
			<hr>
			<!-- row -->
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<!-- footer copyright -->
					<div class="footer-copyright">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</div>
					<!-- /footer copyright -->
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</footer>
	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="{% static 'js/jquery.min.js'%}"></script>
	<script src="{% static 'js/bootstrap.min.js'%}"></script>
	<script src="{% static 'js/slick.min.js'%}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js'%}"></script>
	<script src="{% static 'js/main.js'%}"></script>

home/templates/homebase.html
<!DOCTYPE html>
<html lang="ru">
<head>
   	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>{% block title %}My Home Page{% endblock %}</title>
    <meta name="keywords" content="{% block keywords %}Home Keywords{% endblock %}">
	<meta name="description" content="{% block description %}Home Description{% endblock %}">

    <!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">
    {% load static %}
	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css'%}" />

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css'%}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
    {% block head %}
    {% endblock %}
</head>
<body>
    {% include 'header.html' %}
    {% block sidebar %} {% endblock %}
    {% block slider %} {% endblock %}
    {% block body %} {% endblock %}
    {% block footer %} {% endblock %}
</body>
</html>

home/templates/index.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %}My Home Page{% endblock %}
{% block keywords %}My Home Keywords{% endblock %}
{% block description %}My Home Description{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}
{% block slider %}{% include 'slider.html' %} {% endblock %}
{% block body %} {% include 'content.html' %}{% endblock %}
{% block footer %} {% include 'footer.html' %}{% endblock %}

home/templates/orderproduct.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %}Order Page{% endblock %}
{% block keywords %}{{ category.keywords }}{% endblock %}
{% block description %}{{ category.description }}{% endblock %}
{% block sidebar %}{% include 'sidebar.html' %}{% endblock %}
{% block body %}

    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active"></li>
            </ul>
        </div>
    </div>
    <div class="section">
        <div class="row">
            <form action="" method="post">
                {% csrf_token %}
                <div class="col-lg-6">
                    <div class="billing-details">
                        <div class="section-title">
                            <h4 class="title">Shipping Details</h4>
                        </div>
                        <p><label for="id_first_name">First Name:</label>
                            <input type="text" name="first_name" value="{{ user.first_name }}" class="input" maxlength="15" required id="id_first_name">
                        </p>
                        <p><label for="id_last_name">Last Name:</label>
                            <input type="text" name="last_name" value="{{ user.last_name }}" class="input" maxlength="15" required id="id_last_name">
                        </p>
                        <p><label for="id_address">Address:</label>
                            <input type="text" name="address" value="{{ user.address }}" class="input" maxlength="15" required id="id_address">
                        </p>
                        <p><label for="phone">Phone:</label>
                            <input type="text" name="phone" value="{{ user.phone }}" class="input" maxlength="15" required id="phone">
                        </p>
                        <p><label for="id_city">City:</label>
                            <select name="city" class="input" id="id_city">
                                <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                <option value="Tashkent">Tashkent</option>
                            </select>
                        </p>
                        <p><label for="id_country">Country</label>
                            <input type="text" name="country" class="input" maxlength="15" id="id_country" >
                        </p>
                        <div class="pull-right">
                            <button type="submit" class="primary-btn">Complete Order</button>
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

home/templates/search.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %}{{ query }} Results {% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}

{% block body %}
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">{{ query }}Results</li>
            </ul>
        </div>
    </div>

    <tbody>
    {% for rs in products %}
        <tr>
            <td class="thumb"><a href="/product/{{ rs.id }}/{{ rs.slug }}">
                <img src="{{ rs.image.url }}" style="height: 100px" alt="">
            </a></td>
            <td class="details">
                <a href="/product/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a>
            </td>
            <td class="price text-center"><strong>{{ rs.price }} so'm</strong></td>
            <td class="qty text-right"><input class="input" type="number" value="1"></td>
            <td class="text-right"><a href="/order/addtoshopcart/{{ rs.id }}" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i></a></td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}
{% block footer %} {% include 'footer.html' %}{% endblock %}

home/templates/slider.html
{% load static %}
<!-- HOME -->
	<div id="home">
		<!-- container -->
		<div class="container">
			<!-- home wrap -->
			<div class="home-wrap">
				<!-- home slick -->
				<div id="home-slick">
                    {% for rs in products_slider %}
					<!-- banner -->
					<div class="banner banner-1">
						<img src="{{ rs.image.url }}" alt="" style="height: 550px">
						<div class="banner-caption text-center">
							<h1>{{ rs.title }}</h1>
							<h3 class="white-color font-weak">{{ rs.price}}so'm</h3>
							<a href="/product/{{ rs.id }}/{{ rs.slug }}" class="primary-btn">Shop Now</a>
						</div>
					</div>
					<!-- /banner -->
                     {% endfor %}
					<!-- banner -->
				</div>
				<!-- /home slick -->
			</div>
			<!-- /home wrap -->
		</div>
		<!-- /container -->
	</div>
	<!-- /HOME -->